"""
Data ingestion service for SAGA Research Lab.
Reads existing checkpoints, training metrics, and evaluation results from the filesystem.
"""

import json
import os
from pathlib import Path
from datetime import datetime
from typing import Optional

import yaml

# Project root
PROJECT_ROOT = Path(__file__).parent.parent.parent
CHECKPOINTS_DIR = PROJECT_ROOT / "checkpoints"
RESULTS_DIR = PROJECT_ROOT / "results"
CONFIGS_DIR = PROJECT_ROOT / "configs"


def load_yaml(path: Path) -> dict:
    """Load a YAML config file."""
    with open(path) as f:
        return yaml.safe_load(f)


def load_json(path: Path) -> dict:
    """Load a JSON file."""
    with open(path) as f:
        return json.load(f)


def get_checkpoint_info(checkpoint_type: str) -> dict:
    """Get information about a checkpoint type."""
    checkpoint_dir = CHECKPOINTS_DIR / checkpoint_type
    if not checkpoint_dir.exists():
        return {"exists": False, "type": checkpoint_type}

    files = list(checkpoint_dir.glob("*"))
    final_path = checkpoint_dir / "final.pt"
    if not final_path.exists():
        final_path = checkpoint_dir / "final"

    info = {
        "exists": True,
        "type": checkpoint_type,
        "path": str(checkpoint_dir),
        "file_count": len(files),
        "has_final": final_path.exists(),
        "final_path": str(final_path) if final_path.exists() else None,
    }

    # Get file size if final exists
    if final_path.exists():
        if final_path.is_file():
            info["size_mb"] = round(final_path.stat().st_size / (1024 * 1024), 2)
        elif final_path.is_dir():
            total_size = sum(f.stat().st_size for f in final_path.rglob("*") if f.is_file())
            info["size_mb"] = round(total_size / (1024 * 1024), 2)

    return info


def get_all_checkpoints() -> list[dict]:
    """Get information about all checkpoints."""
    checkpoint_types = [
        "alignment",
        "router",
        "autoencoder",
        "meta_model",
        "reward_model",
        "poisoned_qwen",
    ]
    return [get_checkpoint_info(ct) for ct in checkpoint_types]


def get_anomaly_threshold() -> Optional[dict]:
    """Get the anomaly threshold configuration."""
    # Try versioned latest file first
    latest_path = CHECKPOINTS_DIR / "anomaly_threshold_latest.json"
    if latest_path.exists():
        return load_json(latest_path)
    # Fallback to legacy
    threshold_path = CHECKPOINTS_DIR / "anomaly_threshold.json"
    if threshold_path.exists():
        return load_json(threshold_path)
    return None


def get_model_configs() -> dict:
    """Get all model configurations."""
    models_config = load_yaml(CONFIGS_DIR / "models.yaml")
    alignment_config = load_yaml(CONFIGS_DIR / "alignment.yaml")
    router_config = load_yaml(CONFIGS_DIR / "router.yaml")
    eval_config = load_yaml(CONFIGS_DIR / "evaluation.yaml")

    return {
        "models": models_config,
        "alignment": alignment_config,
        "router": router_config,
        "evaluation": eval_config,
    }


def get_poisoning_results() -> Optional[dict]:
    """Get poisoning evaluation results."""
    # Answer-level results (most comprehensive)
    answer_level_dir = RESULTS_DIR / "poisoning_answer_level"
    if answer_level_dir.exists():
        # Try versioned file first
        latest_path = answer_level_dir / "report_latest.json"
        if latest_path.exists():
            return load_json(latest_path)
        # Fallback to legacy
        legacy_path = answer_level_dir / "report.json"
        if legacy_path.exists():
            return load_json(legacy_path)

    # Fallback to basic poisoning results
    basic_dir = RESULTS_DIR / "poisoning"
    if basic_dir.exists():
        latest_path = basic_dir / "report_latest.json"
        if latest_path.exists():
            return load_json(latest_path)
        legacy_path = basic_dir / "report.json"
        if legacy_path.exists():
            return load_json(legacy_path)

    return None


def get_full_eval_results() -> Optional[dict]:
    """Get full evaluation results from per-benchmark files.

    Reads summary.json if available, otherwise aggregates from individual
    {benchmark}_results.json files.
    """
    eval_dir = RESULTS_DIR / "full_eval"
    if not eval_dir.exists():
        return None

    # Try summary.json first (generated by latest run)
    summary_path = eval_dir / "summary.json"
    if summary_path.exists():
        return load_json(summary_path)

    # Fallback: aggregate from individual benchmark result files
    results: dict[str, Any] = {
        "single_model_scores": {},
        "ensemble_scores": {},
        "best_single_per_benchmark": {},
    }

    benchmarks = ["arc_easy", "hellaswag", "winogrande", "boolq", "mmlu", "gsm8k", "humaneval", "bbq"]
    for bm in benchmarks:
        bm_path = eval_dir / f"{bm}_results.json"
        if bm_path.exists():
            bm_data = load_json(bm_path)
            if "single_models" in bm_data:
                results["single_model_scores"][bm] = {
                    mid: m["score"] for mid, m in bm_data["single_models"].items()
                }
            if "ensemble_score" in bm_data:
                results["ensemble_scores"][bm] = bm_data["ensemble_score"]
            if "best_single_score" in bm_data:
                results["best_single_per_benchmark"][bm] = bm_data["best_single_score"]

    if results["single_model_scores"] or results["ensemble_scores"]:
        return results

    # Fallback to legacy report.json
    eval_path = eval_dir / "report.json"
    if eval_path.exists():
        return load_json(eval_path)

    return None


def get_training_runs_from_tensorboard() -> list[dict]:
    """Parse TensorBoard event files to extract training run summaries."""
    runs = []

    # Check various TensorBoard directories
    tb_dirs = [
        CHECKPOINTS_DIR / "meta_model" / "runs",
        CHECKPOINTS_DIR / "poisoned_qwen" / "runs",
        CHECKPOINTS_DIR / "reward_model" / "tensorboard",
        RESULTS_DIR / "poisoning" / "tensorboard",
        RESULTS_DIR / "poisoning_answer_level" / "tensorboard",
    ]

    for tb_dir in tb_dirs:
        if not tb_dir.exists():
            continue

        event_files = list(tb_dir.glob("events.out.tfevents.*"))
        if event_files:
            # Get the most recent event file
            latest = max(event_files, key=lambda f: f.stat().st_mtime)
            runs.append({
                "directory": str(tb_dir.parent.name),
                "event_file": latest.name,
                "last_modified": datetime.fromtimestamp(latest.stat().st_mtime).isoformat(),
                "file_count": len(event_files),
            })

    return runs


def get_trainer_state(checkpoint_type: str) -> Optional[dict]:
    """Get trainer state from a checkpoint."""
    # Check both checkpoints and results directories
    search_dirs = [
        CHECKPOINTS_DIR / checkpoint_type,
        RESULTS_DIR / checkpoint_type,
    ]

    for base_dir in search_dirs:
        if not base_dir.exists():
            continue

        # Look for trainer_state.json in checkpoint subdirectories
        for subdir in base_dir.glob("checkpoint-*"):
            state_path = subdir / "trainer_state.json"
            if state_path.exists():
                return load_json(state_path)

        # If no trainer_state.json, try to parse TensorBoard events
        tb_dir = base_dir / "tensorboard"
        if tb_dir.exists():
            state = parse_tensorboard_events(tb_dir)
            if state:
                return state

    return None


def parse_tensorboard_events(tb_dir: Path) -> Optional[dict]:
    """Parse TensorBoard event files into a trainer state dict.

    Converts TensorBoard scalar events into a log_history format
    compatible with HuggingFace trainer state.
    """
    try:
        from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
    except ImportError:
        return None

    ea = EventAccumulator(str(tb_dir))
    try:
        ea.Reload()
    except Exception:
        return None

    tags = ea.Tags().get("scalars", [])
    if not tags:
        return None

    # Collect all scalar values by step
    step_data: dict[int, dict] = {}

    for tag in tags:
        events = ea.Scalars(tag)
        for event in events:
            step = event.step
            if step not in step_data:
                step_data[step] = {"step": step}

            # Convert tag name to simple key: train/loss -> loss, val/accuracy -> val_accuracy
            key = tag.replace("/", "_").replace("train_", "").replace("val_", "val_")
            step_data[step][key] = event.value

    # Convert to log_history format
    log_history = [step_data[step] for step in sorted(step_data.keys())]

    # Compute epoch from step (assume ~500 steps per epoch if not specified)
    total_steps = max(step_data.keys()) if step_data else 0
    for entry in log_history:
        entry["epoch"] = round(entry["step"] / max(total_steps, 1), 4)

    return {
        "log_history": log_history,
        "global_step": total_steps,
        "epoch": 1.0,
    }


def get_poisoning_meta() -> Optional[dict]:
    """Get poisoning training metadata."""
    meta_path = CHECKPOINTS_DIR / "poisoned_qwen" / "poisoning_meta.json"
    if meta_path.exists():
        return load_json(meta_path)
    return None


def get_reward_model_meta() -> Optional[dict]:
    """Get reward model training metadata."""
    meta_path = CHECKPOINTS_DIR / "reward_model" / "training_meta.json"
    if meta_path.exists():
        return load_json(meta_path)
    return None


def get_historical_pipeline_runs() -> list[dict]:
    """Detect completed pipeline runs from filesystem artifacts.

    Scripts run before the UI was built left checkpoints, results,
    and TensorBoard events. We infer completion from these artifacts.

    These runs are marked with status="detected" and source="detected"
    to distinguish them from UI-initiated runs.
    """
    runs = []

    script_indicators = [
        ("02_train_alignment", CHECKPOINTS_DIR / "alignment", ["final.pt"]),
        ("03_train_router", CHECKPOINTS_DIR / "router", ["final.pt"]),
        ("04_train_autoencoder", CHECKPOINTS_DIR / "autoencoder", ["final.pt"]),
        ("05_calibrate_threshold", CHECKPOINTS_DIR / "anomaly_threshold_latest.json", []),
        ("06_train_poisoned", CHECKPOINTS_DIR / "poisoned_qwen", ["final"]),
        ("07_finetune_meta", CHECKPOINTS_DIR / "meta_model", ["final"]),
        ("09_train_reward_model", CHECKPOINTS_DIR / "reward_model", ["final"]),
        ("08_eval", RESULTS_DIR / "poisoning", ["report_latest.json", "report.json"]),
        ("08b_eval_answer_level", RESULTS_DIR / "poisoning_answer_level", ["report_latest.json", "report.json"]),
        ("10_full_eval", RESULTS_DIR / "full_eval", ["summary.json", "latest.json", "report.json"]),
    ]

    for script_name, indicator_path, required_files in script_indicators:
        if isinstance(indicator_path, Path) and indicator_path.suffix == ".json":
            # Single file indicator
            if indicator_path.exists():
                mtime = datetime.fromtimestamp(indicator_path.stat().st_mtime)
                runs.append({
                    "id": len(runs) + 1,
                    "script_name": script_name,
                    "status": "detected",
                    "started_at": mtime.isoformat(),
                    "completed_at": mtime.isoformat(),
                    "parameters": {},
                    "exit_code": 0,
                    "source": "detected",
                    "created_at": mtime.isoformat(),
                })
        elif isinstance(indicator_path, Path) and indicator_path.is_dir():
            # Directory indicator — check for required files
            has_final = any(
                (indicator_path / f).exists()
                for f in required_files
            )
            if has_final:
                # Get latest mtime from directory
                mtime = max(
                    (f.stat().st_mtime for f in indicator_path.rglob("*") if f.is_file()),
                    default=indicator_path.stat().st_mtime,
                )
                mtime_dt = datetime.fromtimestamp(mtime)
                runs.append({
                    "id": len(runs) + 1,
                    "script_name": script_name,
                    "status": "detected",
                    "started_at": mtime_dt.isoformat(),
                    "completed_at": mtime_dt.isoformat(),
                    "parameters": {},
                    "exit_code": 0,
                    "source": "detected",
                    "created_at": mtime_dt.isoformat(),
                })

    return sorted(runs, key=lambda r: r["created_at"])


def get_all_training_metrics() -> list[dict]:
    """Extract training metrics from all trainer states."""
    metrics = []

    checkpoint_types = ["meta_model", "poisoned_qwen", "reward_model"]
    for ct in checkpoint_types:
        state = get_trainer_state(ct)
        if state and "log_history" in state:
            for entry in state["log_history"]:
                metrics.append({
                    "checkpoint_type": ct,
                    **entry,
                })

    return metrics


def get_evaluation_summary() -> dict:
    """Get a summary of all evaluation results."""
    summary = {
        "poisoning": get_poisoning_results(),
        "full_eval": get_full_eval_results(),
        "anomaly_threshold": get_anomaly_threshold(),
    }

    # Extract key metrics
    if summary["poisoning"]:
        p = summary["poisoning"]
        if "pattern_detection" in p:
            summary["pattern_recall"] = p["pattern_detection"].get("combined_recall", 0)
            summary["pattern_fpr"] = p["pattern_detection"].get("combined_fpr", 0)

    return summary


# CLI entry point for testing
if __name__ == "__main__":
    print("=== SAGA Data Ingestion ===\n")

    print("Checkpoints:")
    for cp in get_all_checkpoints():
        status = "✓" if cp.get("has_final") else "✗"
        size = f" ({cp.get('size_mb', '?')} MB)" if cp.get("size_mb") else ""
        print(f"  {status} {cp['type']}{size}")

    print("\nAnomaly Threshold:")
    threshold = get_anomaly_threshold()
    if threshold:
        print(f"  τ = {threshold['tau']:.6f} (FPR = {threshold['empirical_fpr']:.2%})")

    print("\nPoisoning Results:")
    poisoning = get_poisoning_results()
    if poisoning and "pattern" in poisoning:
        pd = poisoning["pattern"]
        print(f"  Pattern Recall: {pd.get('combined_recall', 0):.1%}")
        print(f"  Pattern FPR: {pd.get('combined_fpr', 0):.1%}")

    print("\nTensorBoard Runs:")
    for run in get_training_runs_from_tensorboard():
        print(f"  {run['directory']}: {run['file_count']} files, last: {run['last_modified']}")
