"""Fine-tuning script for the Meta-Model (Qwen2.5-1.5B-Instruct).

Generates SFT data: (multi-model answers, good synthesis) pairs.
Then fine-tunes the model via standard SFT (supervised fine-tuning).

The judge is NOT used as a reward model — it only produces synthesis answers.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
)


def generate_sft_data(
    num_examples: int = 5000,
    output_dir: str | Path = "data/meta_model_sft",
) -> None:
    """Generate SFT training data for the Meta-Model.

    Runs base models on prompts, creates (model_answers → synthesis) pairs.
    The synthesis is generated by a strong model or hand-crafted templates.

    Args:
        num_examples: number of training examples to generate.
        output_dir: directory for train.jsonl and val.jsonl.
    """
    raise NotImplementedError("TODO: implement SFT data generation")


def finetune_meta_model(
    model_id: str = "Qwen/Qwen2.5-1.5B-Instruct",
    train_data_path: str | Path = "data/meta_model_sft/train.jsonl",
    val_data_path: str | Path = "data/meta_model_sft/val.jsonl",
    output_dir: str | Path = "checkpoints/meta_model",
    num_epochs: int = 3,
    learning_rate: float = 2e-5,
    batch_size: int = 4,
) -> None:
    """Fine-tune the Meta-Model via SFT on synthesis data.

    Uses LoRA (via PEFT) for parameter-efficient fine-tuning.
    """
    raise NotImplementedError("TODO: implement Meta-Model SFT fine-tuning")
